[package]
name = "icp-practice"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
pcd-rs = { version = "0.11", features = ["derive"] }
plotters = "0.3"

ndarray = { version = "0.15", features = ["blas"] }
ndarray-linalg = { version = "0.16", features = ["openblas-system"] }

rand = "0.8"
ndarray-rand = "0.14"
